producer:
	@echo "Starting Producer..."
	python ./publisher/generator.py 

processor:
	@echo "Starting Processor..."
	python ./processor/processor.py

consumer:
	@echo "Starting Consumer..."
	python ./subscriber/subscriber.py

.PHONY: producer processor consumer
